INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Abén Zaide', 'Andueza, José Maria de');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Ana Oller', 'Orellana, Francisco José de');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Antonio de Lupián Zapata', 'Castro, Adolfo de');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Baron de Lamothe', 'Lamothe - Langon, Etienne-Leon');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Carlos G. Ephebus', 'Garcia Doncel, Carlos');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('El Aventurero', 'Desconocido: El Aventurero');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('El Barón de Illescas', 'Ramirez de Losada, Nicolas');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('El Curioso Parlante', 'Mesonero Romanos, Ramón de ');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('El Licenciado Escribe', 'Eguilaz, Luis de');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('El Solitario', 'Estebanez Calderon, Serafin');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('El Tío Camorra', 'Martinez Villergas, Juan');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('El capitán Bombarda', 'Menendez, Baldomero');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Jean de Falaise', 'Chennevieres-Pointel, Charles-Philippe de');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Juan de Salduba', 'Sazatornil, Juan Antonio');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('La Nereida', 'Desconocido: La Nereida');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Madoz de Aliana, Enriqueta', 'Diaz Fernandez de Lamarque, Antonia');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Marie de l´Épinay', 'Bruchez, Eve de ');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Marqués de Molins', 'Roca de Togores, Mariano');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Pitre Chevalier', 'Chevalier, Pierre-Michel-Francois');
INSERT INTO ALIAS (VALOR, AUTOR_AUTHOR_NAME) VALUES ('Reithra', 'Desconocido: Reithra');