INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un amor y una marica. Episodio de caza', null, 'Crooke, Ramón');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Costumbres. Mi noviciado en la Corte', null, 'Cuasiermas, El Bachiller');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El loco. Leyenda del siglo XIV', null, 'D.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los baños de Graena', null, 'D.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El frac', null, 'D. Y.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Gentil-Zubi. Tradición vizcaína', null, 'Delmas, Juan E.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Donde las dan las toman', null, 'Diana, Manuel Juan');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El dios de los avaros', 'Madoz de Aliana, Enriqueta', 'Diaz Fernandez de Lamarque, Antonia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Conrado', null, 'Diaz, Clemente');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El baile de ánimas', null, 'Diaz, Clemente');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El matrimonio masculino', null, 'Diaz, Clemente');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Metamorfosis no conocida', null, 'Diaz, Clemente');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Rasgo romántico', null, 'Diaz, Clemente');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Sultán y Celinda. Episodio de la historia de los canes', null, 'Diaz, Clemente');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un cuento de vieja', null, 'Diaz, Clemente');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La leyenda de Whittington y de su gato', null, 'Dickens, Charles?');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La Odalisca', null, 'Dominguez, H. V. ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Offland', null, 'Dumas, Alejandro [hijo]');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La corona de siemprevivas. Episodio dramático', null, 'Duran, Manuel P.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Qué día! o Las siete mujeres. Cuento fantástico', null, 'E. U.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('A vista de pájaro. Historia de unos amores', 'El Licenciado Escribe', 'Eguilaz, Luis de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Mi amigo Pepe', 'El Licenciado Escribe', 'Eguilaz, Luis de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cuento. La iglesia subterránea de San Agustín en Tolosa', null, 'Escalante, Juan Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Guanga. Balada', null, 'Escalera, Evaristo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una cita en el desierto', null, 'Escalera, Evaristo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una siesta', null, 'Escalera, Evaristo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El gabán verde', null, 'Escamilla, Pedro');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Estudios de costumbres españolas. Cuadro segundo. ¡Cuando el río suena!', null, 'Escosura, Patricio de la');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Estudios sobre las costumbres españolas. Primer cuadro. Dos desenlaces de un solo drama', null, 'Escosura, Patricio de la');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Vaya un viaje!', null, 'Espan{a, Bernabe');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La visita nocturna', null, 'Espinola, Felix');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡¡Dos amores!!', null, 'Espinola, Francisco de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un capricho. Apuntes para una novela', null, 'Espinola, Ramón');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La sorpresa', 'El Solitario', 'Estebanez Calderon, Serafin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El grupo fósil. Episodio de la conquista del Perú', null, 'F. B.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La Inés. Cuento', null, 'F. F.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Don Juan de Austria o la batalla de Lepanto', null, 'F. F. V.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El alcalde de Cihuela. (Cuento popular)', null, 'F. L.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Al primer tapón zurrapas', null, 'F. R.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El vivac. Cuento', null, 'Fere, Octave');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La semana de los tres domingos', null, 'Fernandez Cuesta, Nemesio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Tres cadáveres', null, 'Fernandez de Jaime, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Visión y realidad', null, 'Fernandez de Jaime, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El amor de una mujer', null, 'Fernandez de los Rios, Angel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Secretos de familia', null, 'Fernandez de los Rios, Angel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La Alameda del Perejil. Novela gaditana', null, 'Flores Arenas, Francisco');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Don Liborio de Cepeda. Lance original semi-serio, con las licencias necesarias para llamarse novela', null, 'Flores, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los pobres vergonzantes', null, 'Frontaura, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Antonio el Siciliano. Anécdota histórica del año 1475', null, 'Fuente, Vicente de la');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Costumbres del lugar. Aventuras de ronda', null, 'Fuente, Vicente de la');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El día de san Blas en Meco', null, 'Fuente, Vicente de la');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El salmón de Alagón', null, 'Fuente, Vicente de la');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Encuentro de Carlos II con el Viático', null, 'Fuente, Vicente de la');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La rabia y los saludadores', null, 'Fuente, Vicente de la');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una carga de caballería', null, 'Fuente, Vicente de la');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Alonso de Moar', null, 'Fulgosio, Fernando');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El prado. Leyenda gallega', null, 'Fulgosio, Fernando');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La corredoira. Leyenda gallega', null, 'Fulgosio, Fernando');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dos mártires. Episodio de la Guerra de África', null, 'G. C. ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La confesión', null, 'Galt, John');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una historia de amores', null, 'Galvez Canero, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El burrero de Túnez', null, 'Gaminde, Pedro Benito de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El perro de Juan Martín', null, 'Garay de Sarti, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Historia de un paraguas', null, 'Garay de Sarti, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Aventuras sentimentales de una horquilla', null, 'Garcia de Luna, Luis');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La tercera dama duende', null, 'Garcia de Quevedo, José Heriberto');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Sin nombre. Recuerdos de viaje', null, 'Garcia de Quevedo, José Heriberto');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un amor de estudiante', null, 'Garcia de Quevedo, José Heriberto');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Costumbres. El poeta en la tertulia de confianza', null, 'Garcia del Real, Luciano');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El reloj de las monjas de San Plácido', 'Carlos G. Ephebus', 'Garcia Doncel, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El guardia del rey. Novela histórica', null, 'Garcia Tejero, Alfonso');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El último remedio', null, 'Gasset y Artime, Eduardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Historia de un clavel', null, 'Gasset y Artime, Eduardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La sombra de un caballero. Balada', null, 'Gasset y Artime, Eduardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El caballero doble', null, 'Gautier, Theophile');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La generosa (Estudio de costumbres)', null, 'Gil Luengo, Constantino');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Alma por alma. Cuento', null, 'Gil Sanz, Alvaro');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Caín y Abel. Novela', null, 'Gil y Baus, Isidoro');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El barbero de un valido. Crónica del siglo XV', null, 'Gil y Baus, Isidoro');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El lago de Carucedo. Tradición popular', null, 'Gil y Carrasco, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El Paso Honroso', null, 'Gil y Zarate, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El cuadro de la chanfaina', null, 'Gimenez Serrano, José ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La buñolera', null, 'Gimenez Serrano, José ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La casa del Duende y las rosas encantadas. Cuento', null, 'Gimenez Serrano, José ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La limpia de Burguillos que lavaba los huevos al freíllos', null, 'Gimenez Serrano, José ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La Virgen del Clavel. Cuento morisco', null, 'Gimenez Serrano, José ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Las tres feas. Cuento mozárabe', null, 'Gimenez Serrano, José ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un abad como hubo muchos, y un cocinero como no hay ninguno', null, 'Godoy Alcantara, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La montaña maldita. Tradición suiza', null, 'Gomez de Avellaneda, Gertrudis');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La velada del helecho o el donativo del diablo. Novela', null, 'Gomez de Avellaneda, Gertrudis');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El eclipse. Coloquios doctrinales de vecindad', null, 'Gonzalez de Tejada, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un amor hasta la China. Novela de costumbres', null, 'Gonzalez de Tejada, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una excursión a Aranjuez', null, 'Gonzalez de Tejada, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('De El Ferrol a Cartagena. Novela-viaje', null, 'Gonzalez Guevara, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El astrólogo y la judía. Leyenda de la Edad Media', null, 'Gonzalez Pedroso, Eduardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Noemía o La flor de los bosques', null, 'Grenet, Elisa');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Historia de Hogan', null, 'Griffin, Gerald');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Guacanajarí', null, 'Güell y Renté, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Amor a la dernière. Artículo com''il faut', null, 'Guerrero, Teodoro');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Memorias de una bella. Novela sui generis', null, 'Guerrero, Teodoro');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Memorias de una fea. Novela en miniatura', null, 'Guerrero, Teodoro');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Costumbres. Los dos estudiantes', null, 'Guillen Buzaran, Juan');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Por lástima…! Historia madrileña', null, 'Gullon, Pio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La unión hipostática', null, 'Gullon, Pio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Rufina o una terrible historia', null, 'Gutierrez de Alba, José Maria');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Don Miguel de Mañara. Cuento tradicional', null, 'Gutierrez de la Vega, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La deuda más olvidada', null, 'Hartzenbusch, Juan Eugenio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La locura contagiosa', null, 'Hartzenbusch, Juan Eugenio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La novia de oro. Cuento en castellano antiguo', null, 'Hartzenbusch, Juan Eugenio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una mártir desconocida o La hermosura por castigo. Cuento moral', null, 'Hartzenbusch, Juan Eugenio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La mancha. Cuento norte-americano', null, 'Hawthorne, Nathaniel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La mano roja', null, 'Hawthorne, Nathaniel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Ricardo Digby, leyenda americana por Nathaniel Hawthorne', null, 'Hawthorne, Nathaniel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La peña de los enamorados', null, 'Honorio, Gonzalo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los Campos Elíseos', null, 'Hostos, Eugenio Maria');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El amor de la castellana. Leyenda', null, 'Iglesias, Santiago');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Recuerdos de la India', null, 'Infante de Palacios, Santiago');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cuento de la Alhambra. El comandante manco y el soldado', null, 'Irving, Washington');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El califa y el astrólogo. Cuento granadino', null, 'Irving, Washington');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un recuerdo a los difuntos', null, 'Iza Zamacola, José de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El barbo de Utebo (Cuento popular)', null, 'J. A.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La voz del anciano', null, 'J. P.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Ahiza. Balada filipina', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Alma bendita', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Amar en fotografía', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Antítesis', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cartas inocentes', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Celia Mazo', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El álbum de retratos', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El espejo roto', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El sexto acto de \La Africana\""', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Ellen', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('En Leganés', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La condesa del Lago', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La estatua de doña Inés', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Lilí', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Lolen', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los tres estados', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Margarita', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Memorias de un aeta', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Memorias de un canario', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Memorias de un tagáloc', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Nuramí', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Rubias y morenas (del libro inédito: \Sueños y realidades\")"', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Tres valientes. Del libro inédito \Sueños y realidades\""', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un abuso de confianza', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un amor sin esperanza', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un caso de avaricia. Del libro inédito \Sueños y realidades\""', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un recuerdo de amor', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un siglo de vida', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una historia azul', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('York', null, 'Fernandez Iturralde, Enrique');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Amor de monja', null, 'Fernandez y Gonzalez, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un episodio histórico', null, 'Fernandez y Gonzalez, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Papel intitulado. Flor de amores', null, 'Fernandez-Guerra y Orbe, Aureliano');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El puñal', null, 'Ferran, Augusto');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La fuente de Montal', null, 'Ferran, Augusto');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cuadros del día. Un retrato al natural', null, 'Ferreiro y Peralta, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Darse al diablo', null, 'Karr, Jean-Baptiste Alphonse');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Las vendedoras de cerezas', null, 'Karr, Jean-Baptiste Alphonse');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El aborrecimiento o La isla desierta', null, 'Kotzebue, August von');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El camello perdido', null, 'L. G.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La venganza generosa', null, 'L. G.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Tertulias del Príncipe de Cambaceres. Napoleón en el Museo de Antigüedades', 'Baron de Lamothe', 'Lamothe - Langon, Etienne-Leon');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Historia primera. ¡En baile! ¡En baile!', null, 'Larra y Wetoret, Luis Mariano de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los dos gallegos. Traducción de una novelita francesa', null, 'Lavallee, Joséph');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La ballena blanca. Historia marina', null, 'Lecomte, Jules');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Recuerdos fantásticos de Galicia. El monasterio de Meira', null, 'Lerroux, Mariano');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Las flores del amor. Narración', null, 'Lopez de la Vega, José ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un episodio de viaje', null, 'Lopez de la Vega, José ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Crónicas de Castilla. Albar Núñez, conde de Lara', null, 'Lopez Martinez, Miguel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El trovador y la infanta. Novela', null, 'Lopez Martinez, Miguel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Leyenda histórica. El alcaide del castillo de Cabezón', null, 'Lopez Martinez, Miguel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Ochenta y tres escalones. Cuento', null, 'Luque, Diego');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una visión', null, 'M. del M. de S.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un cuento de pescador', null, 'M. M. Bartolome');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un romántico más', null, 'M. R. de Q.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Balada en prosa. El conde de Belalcázar', null, 'Madrazo, Pedro de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Balada en prosa. El hidalgo de Arjonilla', null, 'Madrazo, Pedro de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La prisión de Valenzuela. (Rasgo histórico)', null, 'Madrazo, Pedro de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Allá van leyes do quieren reyes', null, 'Magan, Nicolas Vicente');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El Alfaquí de Toledo', null, 'Magan, Nicolas Vicente');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Laras y Castros. 1166', null, 'Magan, Nicolas Vicente');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Autobiografía. Qué cosa es en el día un literato y qué ha venido a ser la vida literaria', null, 'Maldonado y Macanaz, Joaquin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La loca de amor', null, 'Mane y Flaquer, Juan');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Doña Margarita de Austria o grandeza por violencia. Episodio histórico', null, 'Marin y Gutierrez, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cantos populares de Suecia. El castigo ', null, 'Marmier, Xavier');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cantos populares de Suecia. El dolor de Rosalía', null, 'Marmier, Xavier');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cantos populares de Suecia. Hillebrand', null, 'Marmier, Xavier');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dschellaledin. Cuento ruso', null, 'Marmier, Xavier');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Episodio de la guerra de la Independencia en 1809', null, 'Marnier, Jules');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un día de campo', null, 'Martin Redondo, Fernando');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una visita de encargo', null, 'Martin Redondo, Fernando');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Espinas de amor', null, 'Martinez de Velasco, Eusebio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La cruz de sangre. Episodio histórico de la guerra de las comunidades de Castellae', null, 'Martinez de Velasco, Eusebio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Sisalda. Tradición', null, 'Martinez de Velasco, Eusebio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El amor no es plato de pobres', null, 'Martinez Muller Victoriano');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Ayuda de Dios', null, 'Martinez Murguia, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El último recuerdo', null, 'Martinez Murguia, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El sepulcro de Moore', null, 'Martinez Murguia, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Olivia', null, 'Martinez Murguia, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Misterios de una sombra', null, 'Martinez Pedrosa, Fernando');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un hombre por dentro', null, 'Martinez Pedrosa, Fernando');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El calderero de Puerta-Cerrada', 'El Tío Camorra', 'Martinez Villergas, Juan');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una excursión estudiantina', 'El Tío Camorra', 'Martinez Villergas, Juan');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Consecuencias de una taza de café', null, 'Menendez Rayon, Damian');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Costumbres. Un valenciano y un gallego', 'El capitán Bombarda', 'Menendez, Baldomero');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El cáscaro de nuez. Cuento fantástico-marítimo', 'El capitán Bombarda', 'Menendez, Baldomero');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Unas hojas marchitas. Novela', 'El capitán Bombarda', 'Menendez, Baldomero');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Ulrico de Anduz', null, 'Mery, Joséph');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El alquiler de un cuarto', 'El Curioso Parlante', 'Mesonero Romanos, Ramón de ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El duelo se despide en la iglesia', 'El Curioso Parlante', 'Mesonero Romanos, Ramón de ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El recién-venido', 'El Curioso Parlante', 'Mesonero Romanos, Ramón de ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Escenas de guardilla', 'El Curioso Parlante', 'Mesonero Romanos, Ramón de ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La Caja de Ahorros. Cuento moral', 'El Curioso Parlante', 'Mesonero Romanos, Ramón de ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una noche de vela', 'El Curioso Parlante', 'Mesonero Romanos, Ramón de ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('A una mariposa', null, 'Mestre y Marzal, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Miseria y virtud', null, 'Miquel y Roca, Luis');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Ofelia. Leyenda del siglo VI', null, 'Miquel y Roca, Luis');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Amor de hijo. Leyenda', null, 'Miralles de Imperial, Adolfo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Flores y abrojos. Leyenda', null, 'Miralles de Imperial, Adolfo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dos matrimonios. Novela original', null, 'Molina, Ricardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los tipos', null, 'Molina, Ricardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Otra existencia perdida. Novela original', null, 'Molina, Ricardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Una lágrima!', null, 'Moly de Banos, Ricardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Historia de unas botitas', null, 'Moly de Banos, Ricardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El caballero Banda Azul', null, 'Montero y Moralejo, Felix');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El monte del ermitaño. Tradición popular', null, 'Montesinos y Neyra, Juan de Dios');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El paraíso y la Peri', null, 'Moore, Thomas');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Pobre niño!', null, 'Moreno Godino, Florencio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Don Pantaleón. Historia increíble', null, 'Moreno Godino, Florencio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El perdis de la media negra', null, 'Moreno Godino, Florencio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Ideas en cartera', null, 'Moreno Godino, Florencio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La última enamorada', null, 'Moreno Godino, Florencio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La silla del marqués. Novela original', null, 'Moreno Godino, Florencio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los prodigios del amor', null, 'Moreno Godino, Florencio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Rosalía', null, 'Moreno Godino, Florencio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Sueños', null, 'Moreno Godino, Florencio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Tipos madrileños. La tía Malicana', null, 'Moreno Godino, Florencio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un amor increíble. Novela original', null, 'Moreno Godino, Florencio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El caballo del ujier. Leyenda', null, 'Munoz y Gaviria, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La gitana', null, 'Munoz y Gaviria, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La torre del castillo de Olmedo. Leyenda', null, 'Munoz y Gaviria, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los tres judíos', null, 'Munoz y Gaviria, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Quien tal hizo, que tal pague, o el asistente de Sevilla', null, 'Munoz y Gaviria, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Robert''s-Cave en Irlanda', null, 'Munoz y Gaviria, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Rosa la molinera', null, 'Munoz y Gaviria, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('San Lorenzo, mártir', null, 'Munoz y Gaviria, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Entre bastidores', null, 'N. S.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Fenómenos psicológicos. Novela', null, 'Navarrete, Ramón de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un cuento de hadas', null, 'Navarrete, Ramón de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El amor de una reina. Novela', null, 'Navarro Villoslada, Francisco');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El mundo nuevo. Hacer negocios', null, 'Navarro Villoslada, Francisco');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El remedio del amor. Novela', null, 'Navarro Villoslada, Francisco');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La luna de enero', null, 'Navarro Villoslada, Francisco');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Leyendas nacionales. La muerte de César Borja', null, 'Navarro Villoslada, Francisco');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Recuerdos históricos. El castillo de Marcilla', null, 'Navarro Villoslada, Francisco');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El abrazo nupcial. Anécdota', null, 'Navarro, Cecilio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El secreto y el Kanjiar. La ley es la luz', null, 'Navarro, Cecilio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Episodio de la guerra de África. Thacla. Leyenda oriental', null, 'Navarro, Cecilio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La mano de Ayub', null, 'Navarro, Cecilio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Rusia en Polonia (Leyenda)', null, 'Navarro, Cecilio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Lágrimas del alma', null, 'Negro, Rufo de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Galicia monumental. Pórtico antiguo de la calle de Bonaval (Santiago)', null, 'Neira de Mosquera, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Historia de una cabeza. Tradición popular. Año de 1188', null, 'Neira de Mosquera, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Las seis latitudes del amor en Madrid. (Obra inédita)', null, 'Neira de Mosquera, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Bautista Montauban. Cuento', null, 'Nodier, Charles');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La gruta del hombre muerto', null, 'Nodier, Charles');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La hermana Beatriz. Leyenda', null, 'Nodier, Charles');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Azelia y las Willis. Balada', null, 'Nombela, Julio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Delia. Balada', null, 'Nombela, Julio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Delirios y realidades. Impresiones', null, 'Nombela, Julio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dos casos de amor', null, 'Nombela, Julio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cosas de la vida', null, 'Núñez de Arce, Gaspar');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El gorro', null, 'Núñez de Arce, Gaspar');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Historia de mi vecino', null, 'Núñez de Arce, Gaspar');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un caso raro', null, 'Ochoa, Eugenio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una buena especulación', null, 'Ochoa, Eugenio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La joven ambiciosa. Leyenda dinamarquesa', null, 'Oehlenschlager, Adam G.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('A un pícaro otro mayor', null, 'Olona y Gaeta, Luis');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El clavel de la Virgen. (Cuento de vieja)', 'Ana Oller', 'Orellana, Francisco José de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El festín de Baltasar', null, 'Orihuela, Andres Avelino');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La pena del talión', null, 'Orihuela, Andres Avelino');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La venganza de los hombres por la justicia de Dios. Episodio histórico', null, 'Ortega y Frias, Ramón');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un día de campo en La Habana. Recuerdo de un viaje', null, 'Ortiga Rey, Pablo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La hija del loco', null, 'Ossorio y Bernard, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Turigi. (Leyenda histórica) 1609', null, 'Ossorio y Bernard, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un cuento de viejas', null, 'Ossorio y Bernard, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un recuerdo', null, 'Ossorio y Bernard, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una historia... como hay muchas', null, 'Ossorio y Bernard, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El alma de Judas', null, 'P. C.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El amor de moda', null, 'Palacio, Javier de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Hilda (Balada)', null, 'Palacio, Javier de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La margarita (Balada)', null, 'Palacio, Javier de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La vida y la muerte', null, 'Palacio, Javier de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los locos (cuento imitado del indio)', null, 'Palacio, Javier de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los ojos verdes (narración árabe)', null, 'Palacio, Javier de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un baile', null, 'Palacio, Javier de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un casamiento en 1959', null, 'Palacio, Javier de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un caso ', null, 'Palacio, Javier de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una historia sencilla ', null, 'Palacio, Javier de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una noche como pocas', null, 'Palacio, Javier de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Verbena (cuento de vieja)', null, 'Palacio, Javier de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dieu protege la France. (Historia de un Napoleón)', null, 'Palacio, Manuel del');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dios mejora sus horas (Episodios de la vida)', null, 'Palacio, Manuel del');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La cueva de Zampoña', null, 'Palacio, Manuel del');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La locura por amor. Episodio histórico', null, 'Pastor de la Roca, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La prueba del amor', null, 'Pastor de la Roca, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La sombra ensangrentada', null, 'Pastor de la Roca, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los funerales de un vivo, cantados por un difunto', null, 'Pastor de la Roca, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los Palacios de Villena', null, 'Pastor de la Roca, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un casamiento al vapor', null, 'Pastor de la Roca, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una visión de Carlos V', null, 'Pastor de la Roca, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Halewa. Leyenda árabe', null, 'Paz, Abdon de ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La loca de Calella', null, 'Paz, Abdon de ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Viaje por el mundo de los espíritus', null, 'Paz, Abdon de ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Enrique II en el molino de Mansfield', null, 'Percy, Thomas');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('A las Indias', null, 'Pereda, José Maria de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La robla', null, 'Pereda, José Maria de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Al primo albore. Novela original', null, 'Perez Montoto, Salvador');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Lo dejó colgado. (Origen de esta frase)', null, 'Perez-Cossio y Bada, Leandro');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El collar del diablo (Tradición flamenca: versión libre del inglés)', null, 'Prado y Torres, Pedro de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La reina Bona. Crónica polonesa del siglo XVI', null, 'Prado y Torres, Pedro de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Número 17', null, 'Prado y Torres, Pedro de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La calle del Mal Consejo. Tradición segoviana', null, 'Pravia, Carlos de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un recuerdo de Aranjuez', null, 'Principe, Miguel Agustin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El torbellino de nieve. Cuento ruso', null, 'Pushkin, Alexandr');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Celos de gente airada', null, 'R. C.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La noche de bodas', null, 'Rada y Delgado, Fabio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Melancolía', null, 'Rada y Delgado, Fabio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Pobre Mártir! (Episodio Histórico)', null, 'Rada y Delgado, Juan de Dios');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El caballero de Olmedo', null, 'Rada y Delgado, Juan de Dios');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El cuarto del aparecido. (Tradición granadina)', null, 'Rada y Delgado, Juan de Dios');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La calavera del ahorcado. Tradición granadina', null, 'Rada y Delgado, Juan de Dios');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Por un homicidio un hospital. Recuerdo histórico', null, 'Rada y Delgado, Juan de Dios');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Si la hicisteis en Pajares, pagareisla en Campomanes (Tradición granadina)', null, 'Rada y Delgado, Juan de Dios');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El conde don Julián. Conseja cordobesa', null, 'Ramirez de las Casas-Deza, Luis Maria');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Congreso doméstico', 'El Barón de Illescas', 'Ramirez de Losada, Nicolas');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dos almonedas en una. Escenas contemporáneas', 'El Barón de Illescas', 'Ramirez de Losada, Nicolas');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La segunda vez. Cuento fantástico', null, 'Ramos Carrion, Miguel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un tipo en Navidad. El hijo del menestral', null, 'Ramos, Francisco');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Era un ángel!', null, 'Real de Mendoza, Ramón');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Está loca!', null, 'Real de Mendoza, Ramón');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Elfride', null, 'Real de Mendoza, Ramón');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La estrella de la tarde', null, 'Real de Mendoza, Ramón');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Morir sin volverla a ver', null, 'Real de Mendoza, Ramón');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una boda por el sistema de insaculación', null, 'Real de Mendoza, Ramón');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Zaida', null, 'Real de Mendoza, Ramón');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El nido de amor', null, 'Requena Espinar, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La cabra tira al monte', null, 'Requena Espinar, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Recuerdos de un viaje', null, 'Rezusta, Benigno de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un día de caza', null, 'Rezusta, Benigno de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Curar el amor con sanguijuelas', null, 'Rico y Amat, Juan');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El marqués de Lombay', 'Marqués de Molins', 'Roca de Togores, Mariano');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los dos entierros', null, 'Rodriguez Correa, Ramón');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La perla de Nápoles', null, 'Romero y Larranaga, Gregorio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La Virgen del Valle', null, 'Romero y Larranaga, Gregorio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los últimos amores', null, 'Romero y Larranaga, Gregorio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los niños expósitos', null, 'Ros de Olano, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Creo en la virtud', null, 'Rosa Gonzalez, Juan de la');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los amores telegráficos. La vecinita de enfrente', null, 'Rosa Gonzalez, Juan de la');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Juana de Inglaterra', null, 'Rotondo, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La solterona', null, 'Rotondo, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una cometa', null, 'Rotondo, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Madrid en el año 2851. Nuevo porvenir del mundo', null, 'Rua Figueroa, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una representación dramática del siglo XVI', null, 'Rua Figueroa, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La monja de San Payo', null, 'Rua Figueroa, Ramón');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La dama blanca de Lares o el cerro de Masatrigo', 'El Aventurero', 'Desconocido: El Aventurero');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La hija de los bosques. Cuento', 'La Nereida', 'Desconocido: La Nereida');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Miollano. Historia veneciana', 'Reithra', 'Desconocido: Reithra');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La reina Egilona', null, 'A .  ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('María Francisca, o una venta de negros', null, 'A.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El fumador de Haquic o historia de un grano de trigo', null, 'A. C.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('De alto abajo', null, 'A. de la F.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dos poetas', null, 'A. G. G.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una noche en un faro', null, 'A. P.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Antes que te cases mira lo que haces. Proverbio o cuento que se parece a una historia', null, 'Addison, Joséph');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La casa del ahorcado. Tradición', null, 'Aguilar y Lora, Francisco');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Gracias de la infancia', null, 'Alarcón y Fernandez Trujillo, Luis');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Sobre ellas ando', null, 'Alarcón y Fernandez Trujillo, Luis');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Buena pesca! (Tradición aragonesa)', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Viva el Papa!', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Causas célebres. El clavo', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dos retratos', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El afrancesado', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El asistente', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El Ángel de la Guarda. Episodio de la guerra de la Independencia', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El carbonero alcalde. Episodio de la guerra de la Independencia', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El extranjero. Episodio de la guerra de la Independencia', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El rey se divierte', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La buenaventura', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La corneta de llaves', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La cruz de palo. Novela romántica', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Las dos glorias', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los ojos negros', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Novela natural', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Novelas y cuadros de costumbres. La Comendadora', null, 'Alarcón, Pedro Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El boticario Leoncio. Cuento de aldea', null, 'Alfaro Lafuente, Manuel Ibo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Festejos reales. La espada encantada', null, 'Alfaro Lafuente, Manuel Ibo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La cruz de los amantes. Cuento tradicional', null, 'Alfaro Lafuente, Manuel Ibo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una violeta', null, 'Alfaro Lafuente, Manuel Ibo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Desengaños', null, 'Alfaro Lafuente, Timoteo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Las mujeres en tiempo de los patriarcas', null, 'Alonso Valdespino, Camilo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Mujeres de Grecia. Sapho', null, 'Alonso Valdespino, Camilo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Mujeres en Egipto. Cleopatra   ', null, 'Alonso Valdespino, Camilo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Milagros de la vida', null, 'Altadill, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El abeto', null, 'Andersen, Hans Christian');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El cerro de los duendes', null, 'Andersen, Hans Christian');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El príncipe disfrazado', null, 'Andersen, Hans Christian');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El soldado de plomo', null, 'Andersen, Hans Christian');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El traje invisible', null, 'Andersen, Hans Christian');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La boda de oro', null, 'Andersen, Hans Christian');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La flor solitaria', null, 'Andersen, Hans Christian');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La reina de la nieve', null, 'Andersen, Hans Christian');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los dos amantes', null, 'Andersen, Hans Christian');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Carlota Corday. Un episodio de la revolución francesa', 'Abén Zaide', 'Andueza, José Maria de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Costumbres populares. El Morrillo', 'Abén Zaide', 'Andueza, José Maria de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Garci-Laso de la Vega. Episodio histórico del siglo décimo cuarto', 'Abén Zaide', 'Andueza, José Maria de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La capitana. Un episodio de la vida de la marquesa del Encinar', 'Abén Zaide', 'Andueza, José Maria de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La noche grande de Toledo', 'Abén Zaide', 'Andueza, José Maria de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La venta de Aluenda y los arrieros', 'Abén Zaide', 'Andueza, José Maria de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Mariano. Novela de costumbres', 'Abén Zaide', 'Andueza, José Maria de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Amores del rey don Rodrigo con la princesa Eliata', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Anécdota histórica. Episodio de la vida de un gran poeta', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Blanca Capelo. Leyenda veneciana', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El abad y el diablo', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El buque chino. Traducción popular', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El caballero negro. Novela histórica', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El cambio de las edades', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El castillo de Cabra (1340)', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El cochero de Carlos V', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El cofre misterioso del rey Gustavo de Suecia', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El huésped. Parábola', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El nacimiento de Lope de Vega', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El ratón enamorado. Cuento', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El rey depuesto en estatua', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El vaso de madera', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Fantasía. El pájaro en noviembre', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Hernando de Córdoba, el veinticuatro', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La capa roja. Cuento nocturno', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La compra del pavo', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La economía de un real', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La madre del marinero', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La respuesta', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La yerba de virtudes. Cuento', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Las aventuras de Si-Babauri', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los amores de la madreselva y el alhelí', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los dos huérfanos', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Manuel el Rayo. Novela de costumbres', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un elegante de provincia', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un extranjero en Vergara', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un trovador', null, 'Anonimo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Abd-El-Kader-Ben-Salah. Tentativa de asesinato', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Alí y Ahmed', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Alina. Historia del siglo XII', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¿Whig o Tory? Ciudadano', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Chiss... chiss...', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cuento. Lo que encierra una gota de aceite', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El aficionado a los puntos de vista', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El amor de dos huérfanas y la peste. Histórico', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El arco de Fiorillo', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El arco del violinista Fiorillo', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El buque incendiado', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El caballero de Lys', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El castillo de Montrichard o Historia de Guillery. 1606', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El error de un ángel', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El filósofo', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El frisón de la maza. Leyenda', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El grajo adornado con plumas de pavo', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El hombre de mar. Leyenda fantástica', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El hombre feliz a pesar suyo', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El libro de horas', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El minero de Siljan', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El puñal del capuchino', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El rastro sangriento. Leyenda orleanesa', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El salvaje del Brasil', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El tesoro', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Historia del cambista de Bagdad', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Juan Remold de Patkul', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La camisa del hombre feliz', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La cantatriz desconocida. Aventura', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La comedia a la ventana. Dos maridos. Fantasía de una noche de verano', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La elección de un amigo', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La estrella de la mañana', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La maldita', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La resolución', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La rosa misteriosa', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La virgen de Nimes. Episodio histórico', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Las cuentas de tutela', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Lazarina', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Leyenda. Origen de los talismanes de la China', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los aguinaldos de Luciano', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los Colonnes y los Ursin', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los dos primos', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los seguros de vida', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los zapatos de la infanta. Cuento', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Morir sin haber vivido', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Napoleón y el verdugo', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Piedra movediza no cría moho', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Plessis-les Tours. El tiempo del rey Enrique III', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Recuerdos históricos. Un duelo en tiempos de la liga', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Roberto el Diablo', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Si yo fuera rico', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Transmigración del alma de un hombre al cuerpo de una pulga. (Alegoría contra la crueldad con los animales)', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un matrimonio por fuerza', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un Montmorency', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un padrino de lance', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un rayo de sol', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un testamento falso', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una colonia de catalanes', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una hora en una ruina. Recuerdo de la aldea de Montfaucon (Franco Condado)', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una tempestad en los bosques de Neudon', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Ventajas de la adversidad. Cuento moral', null, 'Anonimo - traducciones');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El bastón de diamantes', null, 'Arago, Santiago');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El laceador', null, 'Arago, Santiago');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Amor a vista de pájaro', null, 'Ariza, Juan de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dos flores y dos historias', null, 'Ariza, Juan de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dos secretos. Novela original', null, 'Ariza, Juan de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El caballito discreto', null, 'Ariza, Juan de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El caballo de siete colores', null, 'Ariza, Juan de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La cruz de la esmeralda. Tradición popular', null, 'Ariza, Juan de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La princesa del bien podrá ser', null, 'Ariza, Juan de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Perico sin miedo', null, 'Ariza, Juan de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El resentimiento de un contrabandista', null, 'Azara, Juan Manuel de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Escenas populares. Los bandoleros de Andalucía', null, 'Azara, Juan Manuel de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Edita, la del cuello del cisne. Balada', null, 'Balaguer i Cirera, Victor');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El verdugo. Episodio de la guerra de la Independencia', null, 'Balzac, Honore de ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Historia de un suicidio', null, 'Baralt, Rafael Maria');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Idilios', null, 'Baralt, Rafael Maria');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El espejo de la verdad. Cuento fantástico', null, 'Barrantes, Vicente');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La querida del soldado. Novela original', null, 'Barrantes, Vicente');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Memorias de un pavo', null, 'Becquer, Gustavo Adolfo D.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El marino', null, 'Benisia, Alejandro');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Justicia de Dios', null, 'Benitez Caballero, José Maria');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Estudios de historia natural. El mundo invisible', null, 'Bertsch, Auguste');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El abanico', null, 'Blasco, Eusebio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La cuestión de cuba', null, 'Blasco, Eusebio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El tiesto de albahaca. Caso verdadero', null, 'Boccaccio, Giovanni');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Con mal o con bien a los tuyos te ten. Relación', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Doña Fortuna y don Dinero. Cuento popular', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El vendedor de tagarninas', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Juan Holgado y la muerte. Cuento popular', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Juan Soldado. Cuento popular andaluz recogido por Fernán Caballero', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Justa y Rufina. Relación', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La buena y la mala fortuna. Cuento popular recogido por Fernán Caballero', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La oreja de Lucifer. Cuento popular andaluz recogido por Fernán Caballero', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La suegra del diablo. Cuento popular', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Las ánimas. Cuento andaluz', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los caballeros del pez. Cuento popular del repertorio antiguo refundido por Fernán Caballero', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los dos amigos', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Más largo es el tiempo que la fortuna', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Peso de un poco de paja. Leyenda piadosa', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Sola', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Tribulaciones de un remendero. Cuento popular recogido por Fernán Caballero', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un quid pro quo', 'Fernán Caballero', 'Böhl de Faber, Cecilia');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Vuelvo! Historia de unos amores', null, 'Bonnat, Agustin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Diez y ocho años después', null, 'Bonnat, Agustin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dos ramos de flores', null, 'Bonnat, Agustin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Nunca. Historia de unos amores', null, 'Bonnat, Agustin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Por no saber nadar. Historia de unos amores', null, 'Bonnat, Agustin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un capricho de Cleopatra', null, 'Bonnat, Agustin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un nido de tórtolas. Historia de unos amores', null, 'Bonnat, Agustin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un nido vacío', null, 'Bonnat, Agustin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una punta de cigarro', null, 'Bonnat, Agustin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Yo, ella, nosotros. Historia de unos amores', null, 'Bonnat, Agustin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El amor sin alas', null, 'Bordiu, Eduardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Historia de un libro. Anécdota verídica', null, 'Bordiu, Eduardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Colón. Balada de Luisa Bracmann', null, 'Bracmann, Luisa');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Historia de un puñal corso', 'Marie de l´Épinay', 'Bruchez, Eve de ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Conversión de un incrédulo', null, 'Brunet, C.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Heroísmo de madre. Episodio histórico', null, 'Brunet, C.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Lenorá (Balada alemana)', null, 'Burger, Gottfried August');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El sol de Perico. Cuento que no lo parece', null, 'Bustillo, Eduardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Fantasmagoría', null, 'Bustillo, Eduardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Vidas ajenas. La soirée del señor Pintado', null, 'Bustillo, Eduardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La desposada de Abydos', null, 'Byron, George Gordon');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El ojo del amo', null, 'C.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Costumbres. Los poetas y la melancolía', null, 'C. B.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La torre de Ben-Abil. Novela', null, 'C. B.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La hija de las aguas', null, 'C. R.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Corsos y genoveses. Vannina de Ornano', null, 'Campana, Fabio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La última noche de diciembre (1491). Colón', null, 'Campillo, Narciso');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Desalmado!', null, 'Campos y Carreras, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Maldito fotógrafo! (Páginas de mi vida íntima)', null, 'Campos y Carreras, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Recuerdos de un médico', null, 'Canovas del Castillo, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El hombre de negro. Tradición', null, 'Canovas del Castillo, Serafin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dos diarios en uno. Estudio filosófico', null, 'Carrasco de Molina, Felipe');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dos noches toledanas', null, 'Carrasco de Molina, Felipe');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Historia de un amor desgraciado', null, 'Carreras, Luis ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La cueva de la judía', null, 'Carvajal y Rueda, Froilan');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Leda', null, 'Castilla y Ocampo, Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La mascarada. Novela', null, 'Castro y Serrano, José de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La destrucción de Patria. (Tradiciones gaditanas)', 'Antonio de Lupián Zapata', 'Castro, Adolfo de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Luchar contra la fortuna, novela ejemplar', 'Antonio de Lupián Zapata', 'Castro, Adolfo de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El castillo de Gauzón. Episodio medieval', null, 'Caunedo, Nicolas Castor de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El triunfo del Ave María', null, 'Caunedo, Nicolas Castor de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Tabita. Novela religiosa', null, 'Cervino, Joaquin José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cuentos normandos. El aprisco', 'Jean de Falaise', 'Chennevieres-Pointel, Charles-Philippe de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cuentos morales. Sin casa ni hogar', 'Pitre Chevalier', 'Chevalier, Pierre-Michel-Francois');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La buena hija (cuento)', null, 'Clemente, José Patricio ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El príncipe por un día', null, 'Collin de Plancy, J. - A. - S.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un pintor de muestras', null, 'Comas y Soler, Eusebio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Don Alonso Coronel o la venganza del cielo. Siglo XIV', null, 'Corte y Ruano Calderon, Manuel de la');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Don Juan el Tuerto o el banquete y el suplicio', null, 'Corte y Ruano Calderon, Manuel de la');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Beatrice Cenci. Leyenda', null, 'Costanzo, Salvador');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Guilles de Laval, conocido generalmente con el nombre de Barba Azul', null, 'Costanzo, Salvador');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Mapah. Leyenda contemporánea', null, 'Costanzo, Salvador');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Santa Justina', null, 'Costanzo, Salvador');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un viaje al firmamento', null, 'Costanzo, Salvador');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Aventura horrorosa', null, 'Courier, Paul Louis');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cada loco con su tema', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cuento para niños. El hijo de la fortuna', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Dos historias', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El día de difuntos', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Hazañas de no sé qué príncipe', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La calumnia. Cuento de niños', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La fortuna de la fea. Cuento de niños', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La limosna', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La Noche Buena', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La piedra filosofal. Cuento de niños', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La vida de cualquiera', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('María', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Para no dar aguinaldos', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Por falta de ortografía. Cuento de niños', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Quien malas mañas ha... Cuento antimundano', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Rosa y María. Cuento de niños', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un ángel en el mundo', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Vanitas, Vanitatum', 'Pablo Gámbara', 'Rubio, Carlos');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Proverbios ejemplares. A moro muerto, gran lanzada', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Proverbios ejemplares. Al freír será el reír', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Proverbios ejemplares. Antes que te cases... ', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Proverbios ejemplares. De fuera vendrá quien de casa nos echará', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Proverbios ejemplares. En arca abierta, el justo peca', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Proverbios ejemplares. Escupir al cielo', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Proverbios ejemplares. Hasta los gatos quieren zapatos', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Proverbios ejemplares. Herir por los mismos filos', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Proverbios ejemplares. La mujer del ciego ¿para quién se afeita?     ', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Proverbios ejemplares. Los dedos huéspedes', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Proverbios ejemplares. Mi marido es tamborilero, Dios me lo dio y así me lo quiero', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Tres al saco y el saco en tierra', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una realidad en un sueño', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Yo en compra. Cuento fantástico', null, 'Ruiz Aguilera, Ventura');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Recuerdos históricos. El último discípulo de la escuela granadina (Episodio histórico de la vida de Juan de Sevilla)', null, 'S.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La capilla del perdón', null, 'S. H. B.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Contra pereza diligencia', null, 'Saez de Melgar, Faustina');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El árbol de Natividad. Costumbres alemanas', null, 'Saez de Melgar, Faustina');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Contienda entre el trabajo y la ociosidad', null, 'Saiz Milanes, Julian');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El marqués de Javalquinto', null, 'Salas y Quiroga, Jacinto');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El suspiro de un ángel. Cuento', null, 'Salas y Quiroga, Jacinto');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Moreto', null, 'Salas y Quiroga, Jacinto');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una madre holandesa', null, 'Salas y Quiroga, Jacinto');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un capítulo de las memorias de Julia', null, 'San Roman, Joséfa');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Aventuras de una silla contadas por ella misma', null, 'Sanchez Biedma, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La hermana del quinto', null, 'Sanchez Biedma, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un sueño en el teatro', null, 'Sanz, Eulogio Florentino');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El ruiseñor del harem', 'Juan de Salduba', 'Sazatornil, Juan Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Las tres naranjas y algunas gotas de agua. Cuadro oriental', 'Juan de Salduba', 'Sazatornil, Juan Antonio');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Balada de Schiller', null, 'Schiller, Friedrich von');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Ashavero o el judío errante (Leyenda)', null, 'Schubart, Christian Friedrich Daniel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Ginebra. Novela florentina, según una balada de un cantor de Roma', null, 'Scribe, Eugene');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La vuelta de Juan Pérez', null, 'Selgas y Carrasco, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('A pie y en coche', null, 'Sepulveda y Planter, Ricardo');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Hamlet (Cuento fantástico de Shakespeare)', null, 'Shakespeare, William');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un sueño de amor', null, 'Sodelo, Mario');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Al mejor cazador le va una liebre', null, 'Soler de la Fuente, José Joaquin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Ciento por una. Segunda parte de Jesús el Pobre. Cuento', null, 'Soler de la Fuente, José Joaquin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Cuando enterraron a Zafra. Cuento', null, 'Soler de la Fuente, José Joaquin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Historia de un sombrero verde. (¡Estaba de Dios!)', null, 'Soler de la Fuente, José Joaquin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Jesús el pobre. Cuento', null, 'Soler de la Fuente, José Joaquin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La campana de las tres. Leyenda', null, 'Soler de la Fuente, José Joaquin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La torre de los siete suelos. Tradición granadina', null, 'Soler de la Fuente, José Joaquin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los cabellos de Luisa. Leyenda', null, 'Soler de la Fuente, José Joaquin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los maitines de Navidad. Tradición monástica', null, 'Soler de la Fuente, José Joaquin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Más vale precaver que remediar', null, 'Soler de la Fuente, José Joaquin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El tío Tomás o los zapateros', null, 'Somoza, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La duquesa de Alba y fray Basilio', null, 'Somoza, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La oropéndola en la fuente de la dehesa de la Mora', null, 'Somoza, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Alfredo', null, 'Suero, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Amor poético-prosaico', null, 'Suero, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Mi mejor amiga', null, 'Suero, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Soledad', null, 'Suero, José');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Juan García! Episodio militar', null, 'Tarrago y Mateos, Torcuato');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El compadre Felipe', null, 'Tarrago y Mateos, Torcuato');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La capilla negra', null, 'Tarrago y Mateos, Torcuato');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El ahorcado de palo', null, 'Tejado, Gabino');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La cabellera de la reina. Leyenda', null, 'Tejado, Gabino');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Nuestra señora del Amparo. Leyenda', null, 'Tejado, Gabino');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El español y la veneciana. Novela original', null, 'Tenorio, José Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Emilia Girón', null, 'Tenorio, José Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('De patas en el infierno', null, 'Trueba y la Quintana, Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El más listo que Cardona', null, 'Trueba y la Quintana, Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El perro negro. Cuento popular', null, 'Trueba y la Quintana, Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El tío Miserias (Cuento popular)', null, 'Trueba y la Quintana, Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Jaun-Zuría', null, 'Trueba y la Quintana, Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La portería del cielo. Cuento popular', null, 'Trueba y la Quintana, Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La vida del hombre malo', null, 'Trueba y la Quintana, Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los borrachos', null, 'Trueba y la Quintana, Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Los indianos. Novela original', null, 'Trueba y la Quintana, Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Lozoya y Manzanares', null, 'Trueba y la Quintana, Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Nostalgia', null, 'Trueba y la Quintana, Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Querer es poder. Cuento ministerial', null, 'Trueba y la Quintana, Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Traga-Aldabas. Cuento popular', null, 'Trueba y la Quintana, Antonio de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El paniquesero o La boda grande', null, 'Un aficionado lugaren{o');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El teatro lugareño', null, 'Un aficionado lugaren{o');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Las fiestas del lugar', null, 'Un aficionado lugaren{o');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un bárbaro y un barbero', null, 'Un aficionado lugaren{o');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Después de muerto', null, 'Urcullu Zuleta, Felix Maria de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Matar el tiempo', null, 'Urcullu Zuleta, Felix Maria de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un desafío', null, 'Urcullu Zuleta, Felix Maria de');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('¡Delirio!', null, 'V.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una aristocracia de amor y otra de gloria', null, 'V. B.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Por seguir la corriente. Cuento que pica en historia', null, 'Valcarcel, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un corazón que siente', null, 'Valcarcel, Manuel');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Ángelo', null, 'Valdes, Aureliano');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Fenómeno extraordinario', null, 'Vazquez Valera, Vicente');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El loro de mi vecina', null, 'Vega, Federico de la ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Novela árabe. El amor', null, 'Viardot, Luis');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La corona de fuego ', null, 'Vicetto y Perez, Benito');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La loca de Roupar', null, 'Vicetto y Perez, Benito');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Stellina. Balada', null, 'Vicetto y Perez, Benito');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Amor sin fe. Novela', null, 'Vidart y Schuch, Luis');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Por ti. Novela', null, 'Vidart y Schuch, Luis');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Una cita en el Albaicín', null, 'Vila y Goyri, Francisco');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Episodios históricos. La cruz del rey Don Sancho. Tradición histórica', null, 'Villa, Rafael ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Mal de ojo', null, 'Villalva, Federico');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Las dos levitas', null, 'Villanueva, José Joaquin');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Amalia', null, 'Villanueva, Luis');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Apostasía de un moribundo', null, 'X.');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La independencia  ', null, 'Yago, Pedro  ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('Un capricho. Episodio', null, 'Yago, Pedro  ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('La calle de la traición. (Tradición popular)', null, 'Zamora Caballero, Eduardo ');
INSERT INTO CUENTO (TALE_TITLE, USED_ALIAS, AUTOR_NAME) VALUES ('El hombre de la ilusión y el hombre de la realidad', null, 'Zarraga, J. A. ');