INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Bernal-Francés. Romance portugués', 'Anonimo');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. La tempestad', 'Anonimo');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Mirabeau', 'Anonimo');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El Monasterio de San Lorenzo', 'Anonimo');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Adiós, ilusiones. A la memoria de mi querida madre', 'Anonimo');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Fragmento de un rasgo épico, titulado <em>Un día en Granada</em>', 'Infante de Palacios, Santiago');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La muerte de Jesús (1)', ' Madrazo, Pedro de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Amor correspondido', 'Aguilera, Castor');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Dolores, una rosa', 'Aguilera, Castor');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Dulces amores', 'Aguilera, Castor');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Falacia', 'Aguilera, Castor');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Desacuerdo', 'Aguilera, Castor');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A una nube', 'Aguirre de Tejada, Patricio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la venida del Espíritu Santo. Oda', 'Alarcón, Julio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Adiós a la Mezquita de Córdoba', 'Alarcón, Julio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Un naufragio', 'Albuerne, José María de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('¡Adiós! A don Vicente Barrantes', 'Alcalde Valladares, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A. S....', 'Alejandro');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Dante Alighieri. El Infierno. Canto V', 'Alighieri, Dante');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesías. Literatura extranjera. Zaragoza sitiada y rendida', 'Allen, Henrique');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. A mi Gonzalo', 'Amador de los Ríos, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía histórica. La joya vendida. 1845', 'Amador de los Ríos, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Fragmento de un rasgo épico titulado Un día en Granada', 'Amador de los Ríos, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la primavera', 'Amador de los Ríos, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La juventud', 'Amador de los Ríos, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El alcalde de Antequera. Romance histórico', 'Arellano, C. R. de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. A …', 'Ariza, Juan de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La tempestad. Soneto', 'Armiño, Robustiana');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Solitudine', 'Arnao, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('<span>Poesías. El arrullo de una madre; dedicado a la mía</span>', 'Arnao, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesías. Paz del alma', 'Arnao, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La conquista de Valencia por Jaime I de Aragón', 'Atard, Manuel');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La boticaria de Osuna. Cuento', 'Auset, A.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. La mujer', 'Avelino Benítez, Andrés');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A tus lágrimas', 'Baca y Sevilla, Manuel');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El reclamo', 'Baeza, P. F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. La receta', 'Baeza, P. F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Al cuadro de la Asunción, obra maestra de Rubens, que existe en el museo de pinturas de Valladolid', 'Baeza, P. F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Octava', 'Baeza, P. F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Fábula. El niño y el ciervo', 'Baeza, P. F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Mandatum novum do vobis: diligite proximos vestros sicut vos metipsos', 'Baeza, P. F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Los niños y los pastores', 'Baeza, P. F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El niño y los perros', 'Baeza, P. F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Imitación de Kenfer. A mi amigo M. Vergara', 'Bai, Federico');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la poesía', 'Balaca y Gilabert, Luis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En un álbum', 'Balart, Federico');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Boceto', 'Barco, L. del');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto', 'Barco, L. del');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La despedida', 'Barco, L. del');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Madrigal', 'Barrantes, Vicente');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('¡El rey ha muerto! ¡Viva el rey!', 'Barrantes, Vicente');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Despedida al año de 1859', 'Barrantes, Vicente');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La vida', 'Bermudo y Caamaño, Lucas');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Hernani', 'Boissier, Pedro Alejandro');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La política aplicada al amor. Carta erótica en estilo parlamentario', 'Bretón de los Herreros, Manuel');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La manía de viajar. Epístola satírica a mi amigo, compañero y padrino el señor Don Mariano Roca de Tagores', 'Bretón de los Herreros, Manuel');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. El anónimo', 'Bretón de los Herreros, Manuel');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Varias poesías del siglo XVI. Compuestas por el P. Ignacio Buendía, monje Bernardo del Monasterio de Mon Salud, copiadas de un manuscrito Antiguo. Lamentación contra la lujuria', 'Buendía, P. Ignacio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('<span>Continuación de las poesías del P. Ignacio Buendía, monge Bernardo del Monasterio de Monsalud, y poeta del siglo XVI. Lamentación. A Santa Inés. A San Esteban<br /></span>', 'Buendia, P. Ignacio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En el cumple-años de Emilia. Soneto', 'Bueno, Juan J.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. A mi respetable amigo el Sr. D. J. M. Gallego', 'Bueno, Juan José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Sobre la tumba del poeta Aurelio Aguirre Galarraga', 'Bustillo y Pérez, Eduardo H.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A las puertas de la vida', 'Bustillo y Pérez, Eduardo H.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La niña negra', 'Bustillo y Pérez, Eduardo H.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('¡Al África! Oda', 'Bustillo y Pérez, Eduardo H.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Epigrama', 'Calderón de la Barca, Pedro');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Romance', 'Campillo, Narciso');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Dolora. Ventajas de la inconstancia', 'Campoamor, Ramón de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Dolora. Adiós para siempre. A Carolina', 'Campoamor, Ramón de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Dolora. Últimas abjuraciones', 'Campoamor, Ramón de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Dolora. Glorias de la vida', 'Campoamor, Ramón de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Fragmento', 'Camprodón, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En un álbum', 'Camprodón, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Luz y sombra', 'Cañete, Manuel');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A...', 'Cánovas del Castillo, Serafín');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('No tronchéis las flores (Balada)', 'Cánovas del Castillo, Serafín');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El 18 de sptiembre de 1859 (1). Al Excm. Señor D. Ramón López de Tejada y al Señor D. Juan Pedro Muchada', 'Castro, Adolfo de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Aben-Zulema y Geloyra. Romance morisco', 'Castro, Adolfo de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Inspiración. A mi amigo el Sr. D. Gregorio Romero y Larrañaga', 'Cea, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A las estrellas. Oda dedicada a mi amigo J. M. V.', 'Cea, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Sonetos inéditos de Gutierre de Cetina copiados de un códice que existe en Sevilla en la famosa librería de D. José de Álava y Urbina', 'Cetina, Gutierre de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Salvatori en <em>El Furioso</em>', 'Collar y Bueren');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía', 'Coronado, Carolina');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La rosa blanca', 'Coronado, Carolina');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la señorita doña Robustiana Armiño. La flor del agua', 'Coronado, Carolina');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesías. Tú eres el miedo', 'Coronado, Carolina');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A caza de novia', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El amor de antaño y el de hogaño', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A V***', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A los amantes del matrimonio', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Él y ella', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A mi prima', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Imitación del romancero', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Baco y Venus', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Origen del matrimonio', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Proverbios', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la paz. Oda', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Los mensajeros de amor', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La golondrina', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La voz de amor (en un álbum)', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la señorita doña A*** H***. En su álbum', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A C*** en sus días', 'Corzo y Barrera, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la ciudad de Sevilla por su heroica defensa durante el sitio sufrido el mes de julio de 1843. Oda', 'Cueto, Leopoldo Augusto de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Epigrama', 'Dacarrete, Ángel María');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Otumba. I Méjico', 'Díaz, Juan Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Otumba. II Batalla de Otumba', 'Díaz, Juan Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. El Siglo de Oro. Epístola a Andrés', 'Díaz, Juan Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Romance caballeresco. Aqui comienza la hestorya de la Infantina de Francia, et de como el Infante de Hongría la fizo su namorada ante con ella casar', 'Durán, Agustín');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La mañanica de Sant Joan. Cantar a guisa de coplas del tiempo viejo', 'Durán, N.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Romance caballeresco. Sigue la Hestoria de la Infantina', 'Durán, Agustín');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A mi querido amigo don Francisco Segundo Morontal. La amistad.', 'Eguilaz, Julio de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Las cuatro partes del otro mundo', 'Eguilaz, Luis de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El Dos de Mayo', 'Espronceda, José de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El trovador de la Oceanía', 'F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En un álbum', 'F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Epigrama', 'F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En el álbum de Julia E***', 'F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Al Pásig', 'F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Matilde', 'F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El destino', 'Fenollosa, Amalia');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A María Santísima', 'Fernández  Ruano, Manuel');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Los dos alelíes', 'Fernández Baeza, Pascual');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Al Ser Supremo', 'Fernández Baeza, Pascual');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. La abeja y el grillo', 'Fernández Baeza, Pascual');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Romance', 'Fernández Guerra y Orbe, Luis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A España', 'Fernández Ruano, Manuel');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El Diluvio', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. A Toledo', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Canciones de Beranger. A los jóvenes', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Canciones de Beranger. El viaje imaginario', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Canciones de Beranger. Todavía amores', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Canciones de Beranger. Mi república', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Canciones de Beranger. El judío errante', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Canciones de Beranger. Recuerdos del pueblo', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Canciones de Beranger. Las aves', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Canciones de Beranger. El canto del cosaco', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Canciones de Beranger. ¡Maldita primavera!', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. A la luna', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Canciones de Beranger. La madre ciega', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Canciones de Beranger. La Primavera y el Otoño', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La noche serena. A mi amigo D. P. J.', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Versos escritos a bordo de la fragata Rosa, primera de Cádiz; y dedicados a su capitán el teniente de navío don José Villalba', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Recuerdos de América. Fragmento', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Juventud y ancianidad. A mi amigo D. F. M. en sus días', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Copla escrita al frente de una colección de canciones manuscritas, de M.', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Plegaria de un epicúreo escrita en las Catacumbas', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Mi contemporánea', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Passy', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Canciones de Beranger. El suicidio. A la muerte de los jóvenes Víctor Escousse y Augusto Lebras', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Canción de Beranger. Trece a la mesa', 'Ferrer del Río, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('¡Ay amor, como me has puesto! Romance', 'Flores Arenas, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Lances de Madrid. La casa de juego', 'Flores, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Columna y cuarto de Orijinal <em>sic</em>', 'Flores, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En un álbum. Sonetos', 'Flores, ¿Antonio?');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Música celestial', 'Flores, ¿Antonio?');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Isabel la Católica. Soneto', 'García de la Foz, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A León', 'García de la Foz, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Cántiga', 'García de la Foz, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Suspiros de una madre', 'García de la Foz, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Letrilla. ¡Qué bonito!', 'García de la Foz, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La rosa y el tulipán. En el álbum de…', 'García de la Foz, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Dolora', 'García de la Foz, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Epigrama', 'García de la Foz, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El poder de los recuerdos', 'García de la Foz, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Meditación religiosa', 'García y Tassara, Gabriel');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la eminente artista Elena D''Angri en la romanza ¡O<em>h mio figlio</em>! cantada en el concierto sacro la noche del 15 de abril de 1859 en el teatro de Jovellanos. Soneto', 'Gargollo, Fernando José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Aurora A***', 'Gargollo, Fernando José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En el álbum de la señorita doña Julia Bonnat', 'Gargollo, Fernando José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En el álbum de la señorita doña Fernanda de Autrán', 'Gargollo, Fernando José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Pregunta de niña y respuesta de ángel. Balada', 'Gasset Artime, Eduardo');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Plegaria de amor', 'Gelabert, M.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El chapín del rey o parras verdes. Jácara portuguesa', 'Gil, Isidoro');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Literatura extranjera. Miragaya', 'Gil, Isidoro');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Literatura extranjera. Tradición portuguesa. Miragaya', 'Gil, Isidoro');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Al Monumento del Dos de Mayo. Soneto', 'Gómez de Avellaneda, Gertrudis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A S. M. la Reina Doña María Cristina de Borbón', 'Gómez de Avellaneda, Gertrudis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. El recuerdo inoportuno', 'Gómez de Avellaneda, Gertrudis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La noche de insomnio y el alba. Fantasía', 'Gómez de Avellaneda, Gertrudis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Saludo a Cuba', 'Gómez de Avellaneda, Gertrudis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. A Pepita V. y R.', 'Góngora y Palacio, J. de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Placeres oficiales', 'González  de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El valle de lágrimas', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Las doncellas de Mahoma', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Madrid y el Pardo. Fragmento épico', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Las estaciones matritenses', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Hallazgo de una novia', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Idilio callejero', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Vivir soñando', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Seguidillas', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Gracias del amor', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La humanidad reformada', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En un álbum', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Manual de la felicidad', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Las musas y yo', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El parterre del Retiro', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La primera verbena', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Dos menos', 'González de Tejada, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A mis queridas amigas las señoritas doña Dolores y doña Carolina Martínez. Consejos de una madre a su hija.', 'Grassi, Ángela');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la señora doña Dolores de Toral, en la muerte de su hija, la joven y malograda poetisa doña Alejandra Toral', 'Grassi, Ángela');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('<span>Poesías. La rosa y la violeta. A Julia.</span>', 'Grijalba, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Las promesas del ambicioso. Cuento', 'Grijalva, José de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Canción de un prisionero', 'Grossi, Tomasso');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Meditación', 'Güel y Renté, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Despedida de Cuba', 'Güell y Renté, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesías. Juicio del año de 1848', 'Guerrero, Teodoro');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('¡Al África!', 'García de la Foz, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la Reina Doña Isabel II. Coplas en castellano antiguo', 'Hartzenbusch, Juan Eugenio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La tierra de los cojos. (De Gellert)', 'Hartzenbusch, Juan Eugenio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La madre y el alma inocente', 'Hartzenbusch, Juan Eugenio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La regla general', 'Hartzenbusch, Juan Eugenio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El plantador', 'Hartzenbusch, Juan Eugenio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La joya milagrosa', 'Hartzenbusch, Juan Eugenio de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Un recuerdo. Soneto', 'Henao y Muñoz, Manuel');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('¡Pobre mártir! Balada', 'Hernández, Enrique');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Al partir de La Habana', 'Hernández, Enrique');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La alondra y el águila. En el álbum de María del Pilar Sinués de Marco', 'Hernández, Enrique');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Su nombre', 'Hernández, Enrique');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La paloma. Balada', 'Hernández, Enrique');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En un álbum. A Esperanza', 'Hernández, Enrique');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El tiempo. Oda', 'Herranz de Gonzalo, J.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Traducción de Víctor Hugo', 'Hugo, Víctor');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía (Traducción de Víctor Hugo) A una joven', 'Hugo, Víctor');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. La mariposa', 'Hurtado, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Toros. Primera media corrida de la presente temporada. Madrid, 5 de abril de 1858', 'Infante de Palacios, Santiago');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Toros. Segunda media corrida de la presente temporada', 'Infante de Palacios, Santiago');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Toros. Tercera media corrida de la primera temporada', 'Infante de Palacios, Santiago');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Toros. Quinta media corrida de la primera temporada. Madrid, 3 de mayo de 1858.', 'Infante de Palacios, Santiago');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A un poeta', 'J. P. C.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('¡Cantabria! A las diputaciones de las provincias vascongadas', 'L.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Amor gramático', 'Lacort, J. M. ');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Las hojas de otoño', 'Larrea, José María de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A don Francisco Rodríguez Zapata, mi amigo. Romance', 'Lista, Alberto');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('¡Lágrimas!!...', 'López García, Bernardo');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El día de difuntos ante la tumba de Espronceda', 'López García, Bernardo');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La tempestad', 'López García, Bernardo');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El sol', 'Loren y la Hoz, Juan A.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El águila del Retiro', 'Loren y la Hoz, Juan A.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El eclipse', 'Loren y la Hoz, Juan A.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('¡Bendita seas!! A mi querida madre', 'Loren y la Hoz, Juan A.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Trabajo inútil', 'Madrazo, Pedro de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Primera Mesenia de Tirteo', 'Madrazo, Pedro de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Los caminos de hierro. El sueño del orgullo', 'Madrazo, Pedro de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Sonetos <em>A la muerte del Redentor </em>y a<em> La muerte de</em> <em>Judas</em>,traducidos del italiano por D. José Zorrilla', 'Manzoni, Onofrio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poder de la mujer. A las señoritas doña Dolores y doña Carolina Martínez', 'Martín y Santiago, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Dios', 'Martín y Santiago, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Contrastes de amor', 'Martín y Santiago, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Siempre tú', 'Martín y Santiago, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Epigramas', 'Martínez Muller, Victoriano');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A buen hambre no hay pan duro', 'Martínez Villergas, Juan');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Un hombre extravagante', 'Martínez Villergas, Juan');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Canto del poeta', 'Matta, Guillermo');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La bouquetiere aveugle / La florista ciega', 'Maury, Juan María');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesías. Gozar durmiendo', 'Mestre y Marzal, Carlos');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Carolina', 'Mobellán, Sebastián de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Serenata', 'Mobellán, Sebastián de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Matilde', 'Mobellán, Sebastián de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Toledo', 'Monroy, J. M.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Al señor don Emilio Castelar en la muerte de su madre', 'Monroy, J. M.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Isidoro Márquez', 'Monroy, J. M.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Sonetos traducidos del italiano por D. José Zorrilla a la muerte de Judas (1)', 'Monti, Vincenzo');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La niña de quince años', 'Moreno Morales, Eduarda');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Eres la luz de mi alma', 'Moreno Morales, Eduarda');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. A mi querido amigo el señor don Juan Pascual Romero en la muerte de su malograda hija Julia', 'Murciano, C.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El genio', 'Martínez Monroy, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Dolores', 'Martínez Monroy, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La profanación del templo. Ejemplo bíblico', 'Navarro Villoslada, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La Princesa de Viana. Novela histórica', 'Navarro Villoslada, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A mi querido padre. Alegoría', 'Nombela, Julio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Curioso romance donde se refieren la vida y aventuras del maestro Tirso de Molina', 'Núñez de Arce, Gaspar');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. La flor de la esperanza', 'Olona, Luis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Jesús crucificado', 'Olona, Luis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Fray Luis de León', 'Ortiz Gallardo, Juan');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En un álbum. A Luisa M…', 'Palacio, Javier de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El chambergo', 'Pérez, F.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Fábulas', 'Pino, Luis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Canción', 'Pino, Luis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('España cautiva. Oda', 'Pizarroso, Carlos');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la venida del Mesías. Oda', 'Pizarroso, Carlos');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A mi muy querida hija Emilia', 'Príncipe, Miguel Agustín');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. En el álbum de un viudo', 'Príncipe, Miguel Agustín');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Letrilla', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Un consejo', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A las ruinas de un templo', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Delirio', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la muerte de Jesús', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Fragmento de un poema. A mi querida tía, la Exma. e Illma. Sra. doña Ángela Suárez de Requena. La luz', 'Requena Espinar, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A una Rosa', 'Riego Pica, Francisca Carlota del ');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('¿Por qué canto?', 'Riego Pica, Francisca Carlota del');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Al eminente escultor D. José Piquer, por su bellísima estatua de Cristóbal Colón', 'Riego Pica, Francisca Carlota del');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Recuerdos de Salamanca. Romance II. El hospedaje en el campo. A la E. del M.', 'Roca de Togores, Mariano');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Recuerdos de Salamanca. A Laura en el campo. Romance II', 'Roca de Togores, Mariano');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Recuerdos de Salamanca. A Lesbia. La nube. Romance III', 'Roca de Togores, Mariano');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Al señor don Alberto Lista y Aragón en su regreso a Sevilla en 1844 para fijar en esta ciudad su residencia', 'Rodríguez Zapata, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. Al sol en el oriente', 'Rodríguez Zapata, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. Al señor Don Juan Nicasio Gallego', 'Rodríguez Zapata, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. A mi amigo el distinguido artista D. Antonio Bravo', 'Rodríguez Zapata, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. Al gran rey San Fernando, conquistador y defensor de Sevilla, en el día de su celebridad', 'Rodríguez Zapata, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. A una rosa. Al señor Don Alberto Lista y Aragón', 'Rodríguez Zapata, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Al señor Don Alberto Lista y Aragón en el día de su cumpleaños', 'Rodríguez Zapata, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A mi hijo dormido', 'Romea, J.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El paseo', 'Romea, J.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Cristo en la cruz. Soneto', 'Romea, J.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('¡Malvina!', 'Romero Larrañaga, Gregorio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Mi esperanza es un sueño. Canción', 'Romero Larrañaga, Gregorio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. La fe en el desengaño', 'Romero Larrañaga, Gregorio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Un recuerdo a Estambul', 'Romero Larrañaga, Gregorio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Meditación', 'Rosell, Cayetano');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Epigrama', 'Rotondo, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Nuestra Señora de los Dolores. Himno', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Los semejantes (Fragmento de una leyenda inédita)', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Un ¡ay! del alma', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Jesús. Soneto', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El libro del valle', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El mendigo. Soneto', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Colón', 'Saavedra, Ángel de. Duque de Rivas');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Nieblas del alma', 'Sabando, A. Luis de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('El sombrero y el hongo. Diálogo', 'Sabando, A. Luis de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Lo negro de tus ojos', 'Sabando, A. Luis de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A un necio niño', 'Salas Quiroga, Jacinto de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Murillo. Con motivo de la erección de su estatua en Sevilla', 'Sánchez del Arco, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Oda a España', 'Sánchez del Arco, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La Granadina. Marcha guerrera dedicada a S.M. la reina doña Isabel II de Borbón', 'Serrano de Wilson, Emilia');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Valencia', 'Serrano de Wilson, Emilia');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. A Napoleón', 'Sierra y L., A.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La vuelta de las aves', 'Sinués de Marco, María del Pilar');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La Buñolera. Canción española por Mariano Soriano Fuertes', 'Soriano Fuertes, Mariano');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Epigrama', 'Sabando, A. Luis de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A don Pedro Vergel, alguacil de corte', 'Tarsis, Juan de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Revista quincenal', 'Tejada, Joaquín María de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('¡Todos somos hermanos!', 'Tejada, Joaquín María de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Anacreóntica. Ayer, hoy y mañana', 'Tejada, Joaquín María de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Fábula. La brisa y el cardo', 'Tejado, Gabino');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Ecos del valle', 'Tejado, Gabino');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Sueño de sueños', 'Tejado, Gabino');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Espronceda', 'Tejado, Gabino');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Paisaje en la montaña', 'Tejado, Gabino');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La Noche Buena', 'Tejado, Gabino');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Satanás en el Gólgota', 'Tejado, Gabino');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La Diana', 'Tejado, Gabino');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En el cumpleaños de una niña', 'Toral y Hevia, Alejandrina');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En el álbum de mi esposa', 'Valdelomar y Pineda, Javier');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesías. El fuego divino', 'Valera, Juan');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. La belleza ideal. Cuento fantástico', 'Valera, Juan');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Sin forma', 'Valera, Juan');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La aurora del Viernes Santo', 'Valladares y Garriga, L.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la invicta Sevilla. Bombardeada por Espartero', 'Valladares, Luis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Octava. A Calderón', 'Valladares, Luis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('En el álbum de C. M.', 'Vázquez Queipo, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Indigestión de oratoria', 'Vélez de Guevara, Luis');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Los castores', 'Vergara, M.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La red. Fábula (de una colección inédita)', 'Vergara, M.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La mensajera (Del libro inédito <em>Cuentos de la Villa</em>)', 'Viedma, Juan A.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La fiesta campestre', 'Viedma, Juan A.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Mi parecido en la Corte. Romanza desentonada', 'Viedma, Juan A.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La lavandera', 'Viedma, Juan A.');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Una madre que ve morir a su hija', 'Vila y Blanco, Juan');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Anacreóntica', 'Villalva, Federico');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La sonrisa de Dios', 'Villamartín, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Misterio', 'Vinageras, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A Molière', 'Vinajeras, Antonio');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A las campanas', 'Zea, Francisco');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Pentápolis', 'Zorrilla, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Pentápolis. Canto segundo', 'Zorrilla, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Himno', 'Zorrilla, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Retrato de Al-Hamar el Magnífico', 'Zorrilla, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Poesía. Leyenda de Al-Hamar el Magnífico', 'Zorrilla, José');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Uno de tantos', 'Barrantes, Vicente');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('La niña llorona', 'Barrantes, Vicente');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A la muerte del Salvador', 'Borja y Aragón, Francisco de');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soledad VII. Los pompeyos en los campos de Munda', 'Estébanez Calderón, Serafín');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. A la ciudad de reina de Andalucía', 'Estébanez Calderón, Serafín');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. La reconvención', 'Estébanez Calderón, Serafín');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. La vida en la muerte', 'Estébanez Calderón, Serafín');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A don Alfonso el Sabio. Soneto', 'Estébanez Calderón, Serafín');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Toros. Segunda corrida de la presente temporada', 'Infante de Palacios, Santiago');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Toros. Sexta media corrida de la Primera temporada', 'Infante de Palacios, Santiago');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('A una flor que era un recuerdo', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('España vencedora', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Epigrama', 'Real de Mendoza, Ramón');
INSERT INTO HACE_COLABORACION (COLABORACIONES_TITULO, AUTOR_NAME) VALUES ('Soneto. A la fausta reaparición de la escarapela Roja en el ejército español', 'Estébanez Calderón, Serafín');