INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Antes que te cases mira lo que haces. Proverbio o cuento que se parece a una historia', 'Anónimo');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Balada de Schiller', 'Vinajeras, Antonio');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Cantos populares de Suecia. El castigo ', 'Comas y Soler, Eusebio');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Cantos populares de Suecia. El dolor de Rosalía', 'Comas y Soler, Eusebio');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Cantos populares de Suecia. Hillebrand', 'Comas y Soler, Eusebio');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Dschellaledin. Cuento ruso', 'Fernández Cuesta, Nemesio');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('El amor de dos huérfanas y la peste. Histórico', 'Muñoz y Gaviria, José');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('El arco de Fiorillo', 'Igualada, Juan Ramón');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('El error de un ángel', 'A. F.');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('El filósofo', 'Real de Mendoza, Ramón');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('El frisón de la maza. Leyenda', 'Muñoz y Gaviria, José');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('El hombre de mar. Leyenda fantástica', 'Muñoz y Gaviria, José');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('El paraíso y la Peri', 'Böhl de Faber, Cecilia');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('El torbellino de nieve. Cuento ruso', 'Fernández Iturralde, Enrique');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('El verdugo. Episodio de la guerra de la Independencia', 'R. G.');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('El vivac. Cuento', 'Anónimo');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Enrique II en el molino de Mansfield', 'J. C. N.');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Estudios de historia natural. El mundo invisible', 'Anónimo');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Ginebra. Novela florentina, según una balada de un cantor de Roma', 'Anónimo');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Hamlet (Cuento fantástico de Shakespeare)', 'Comas y Soler, Eusebio');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Historia de un puñal corso', 'Comas y Soler, Eusebio');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Historia del cambista de Bagdad', 'Simonet, J. J.');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Juan Remold de Patkul', 'Anónimo');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('La cantatriz desconocida. Aventura', 'E. B. J.');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('La desposada de Abydos', 'Caula, Remigio');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('La joven ambiciosa. Leyenda dinamarquesa', 'Rivera, César');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('La mancha. Cuento norte-americano', 'Fernández Iturralde, Enrique');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('La rosa misteriosa', 'Muñoz y Gaviria, José');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('La virgen de Nimes. Episodio histórico', 'Comas y Soler, Eusebio');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Las cuentas de tutela', 'Muñoz y Gaviria, José');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Las vendedoras de cerezas', 'Taboada, M. V.');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Lazarina', 'A. A.');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Lenorá (Balada alemana)', 'A. C. [Cueto, Leopoldo Augusto de]');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Miollano. Historia veneciana', 'Muñoz y Gaviria, José');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Transmigración del alma de un hombre al cuerpo de una pulga. (Alegoría contra la crueldad con los animales)', 'Mieg, Juan');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Un padrino de lance', 'Muñoz y Gaviria, José');
INSERT INTO HACE (TRADUCCIONES_TITULO, TRADUCTOR_NOMBRE) VALUES ('Una hora en una ruina. Recuerdo de la aldea de Montfaucon (Franco Condado)', 'A. F.');