INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Antes que te cases mira lo que haces. Proverbio o cuento que se parece a una historia', null, 'Manuel Lucifer');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Balada de Schiller', 'Die Bürgschaft', 'Antonio Vinajeras');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Cantos populares de Suecia. El castigo ', 'Le chatiment', null);
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Cantos populares de Suecia. El dolor de Rosalía', 'La douleur de Rosalie', null);
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Cantos populares de Suecia. Hillebrand', 'Hillebrand', 'T.-E. Comas y Soler');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Dschellaledin. Cuento ruso', 'Dschellaledin', null);
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('El amor de dos huérfanas y la peste. Histórico', 'Bessy Bell and Mary Gray', 'J. M. G.');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('El arco de Fiorillo', null, 'Juan Ramón Igualada');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('El error de un ángel', null, 'A. F.');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('El filósofo', null, null);
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('El frisón de la maza. Leyenda', null, 'José Muñoz y Gaviria');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('El hombre de mar. Leyenda fantástica', null, 'J. M. G.');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('El paraíso y la Peri', 'Paradise and the Peri', 'Fernán Caballero');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('El torbellino de nieve. Cuento ruso', 'Метель', 'F.');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('El verdugo. Episodio de la guerra de la Independencia', 'El verdugo', 'R. G.');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('El vivac. Cuento', 'Une Veillée Normande', null);
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Enrique II en el molino de Mansfield', 'The King and the Miller of Mansfield', 'J. C. N.');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Estudios de historia natural. El mundo invisible', 'Études d''''histoire naturelle. Le monde invisible', 'V.');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Ginebra. Novela florentina, según una balada de un cantor de Roma', 'Guido et Ginebra ou la peste de Florence', null);
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Hamlet (Cuento fantástico de Shakespeare)', null, 'E. Comas y Soler');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Historia de un puñal corso', 'Simple histoire d''un pugnard corse', 'E. Comas y Soler');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Historia del cambista de Bagdad', 'Historia del cambista Abu-l-Hasán Al-Jurasani y de Sacharat Al-Durr', 'J. J. Simonet');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Juan Remold de Patkul', null, null);
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('La cantatriz desconocida. Aventura', null, 'E. B. J.');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('La desposada de Abydos', 'The Bride of Abydos', 'Remigio Caula');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('La joven ambiciosa. Leyenda dinamarquesa', 'Agnette og Havmanden', 'César Rivera');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('La mancha. Cuento norte-americano', 'The Birthmark', 'F.');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('La rosa misteriosa', null, 'José Muñoz y Gaviria');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('La virgen de Nimes. Episodio histórico', null, 'T.-E. Comas y Soler');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Las cuentas de tutela', null, 'José Muñoz y Gaviria');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Las vendedoras de cerezas', 'Les marchandes de cerises', 'M. V. Taboada');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Lazarina', null, 'A. A. ');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Lenorá (Balada alemana)', 'Lenore', 'A. C.');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Miollano. Historia veneciana', 'The Fiery Vault', 'José Muñoz y Gaviria');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Transmigración del alma de un hombre al cuerpo de una pulga. (Alegoría contra la crueldad con los animales)', null, null);
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Un padrino de lance', null, 'José Muñoz y Gaviria');
INSERT INTO TRADUCCIONES (TITULO, TITULO_ORIGINAL, FIRMA) VALUES ('Una hora en una ruina. Recuerdo de la aldea de Montfaucon (Franco Condado)', null, null);